### ISSUE TITLE
FP: Screening done: If one selects screening method say VIA and results as negative, the details containing the VIA and results disappear from the UI.

### ISSUE THREAD

**Issue by pwanjiru** [bespokeinteractive/fpapp#21]
Screening done: If one selects screening method say VIA and results as negative, the details containing the VIA and results disappear from the UI.

Suggestion
-Display method and result selected in UI.

**Comment by daugmaud** [comment]
Concepts were missing. This has been fixed

**Comment by pwanjiru** [comment]
fixed and tested
