### ISSUE TITLE
Screening methods and results not indicated in the UI on “FP SUMMARY & CONFIRMATION” page. 

### ISSUE THREAD

**Issue by pwanjiru** [bespokeinteractive/fpapp#23]
Screening methods and results not indicated in the UI on “FP SUMMARY & CONFIRMATION” page. 

Suggestion: 
Display screening method used and results in the FP summary & confirmation page instead of a message saying “done”

**Comment by daugmaud** [comment]
It only indicates what has been filled. If someone selects Screening Done, and doesn't specify the method or the result. Thats the time it says Done. Otherwise, it will indicate the Method and the results. Or Completely NOT DONE, if that route was chosen

**Comment by pwanjiru** [comment]
Fixed and tested
