### ISSUE TITLE
Quantity used should be auto-set to 1 for any FP method involving a device that’s inserted.

### ISSUE THREAD

**Issue by pwanjiru** [bespokeinteractive/fpapp#26]
Quantity used should be auto-set to 1 for any FP method involving a device that’s inserted.

**Comment by daugmaud** [comment]
Quantity has been set for devices whose method is insertion.
Further, Those methods which are either Procedures or Natural methods, Quantity option has been disabled

**Comment by pwanjiru** [comment]
tested
