### ISSUE TITLE
If a user selects an FP method, then changes it, the changes are not reflected in the FP Summary & confirmation page.  The user has to go back and change details such as Return Date to view changes made for FP method in the FP summary page.

### ISSUE THREAD

**Issue by pwanjiru** [bespokeinteractive/fpapp#27]
If a user selects an FP method, then changes it, the changes are not reflected in the FP Summary & confirmation page.  The user has to go back and change details such as Return Date to view changes made for FP method in the FP summary page.

**Comment by daugmaud** [comment]
This has been done

**Comment by pwanjiru** [comment]
Has been fixed and tested
