### ISSUE TITLE
Cervical Cancer screening: FP module

### ISSUE THREAD

**Issue by pwanjiru** [bespokeinteractive/fpapp#4]
This applies for both PNC & FP clients:
1. If first visit to FP & PNC, screening is mandatory.
2. In no lesion seen, repeat after 5years
3. If lesion seen and screening test is -ve, repeat cervical cancer screening yearly.
4. I client is HIV +ve, with or without lesion, repeat screening yearly.

**Comment by daugmaud** [comment]
This has already been done

**Comment by pwanjiru** [comment]
FIXED AND TESTED
